- backport/backport_pr.py
Closes https://github.com/python/miss-islington/issues/9
> Trigger backport on label change

- backport/tasks.py
> Abort correctly

- backport/backport_pr.py
See https://github.com/python/cpython/pull/3472#issuecomment-328288622
> Text formatting looks weird on GitHub

- backport/delete_branch.py
- backport/util.py
> Delete a branch when PR is closed (either merged or not).

- backport/__main__.py
- backport/backport_pr.py
- backport/status_change.py
- backport/tasks.py
- backport/util.py
Leave a comment when status checks for the backport PR is done.
Only leave the comment on backports made by @miss-islington.
Mention the original PR author and the core dev who merged the original PR.
Closes https://github.com/python/miss-islington/issues/26
> Comment on backport PR when status check is done.

- backport/tasks.py
Closes https://github.com/python/miss-islington/issues/29
> Show the cherry_picker command when backport failed

- backport/backport_pr.py
Fixes https://github.com/python/miss-islington/issues/35
> Only backport if the newly added label is the 'needs backport' label.

- .travis.yml
- dev-requirements.txt
- tests/test_util.py
> Wrote some unit tests.

- backport/tasks.py
- requirements.txt
Only add the branch prefix to the PR title.
Use cherry_picker v0.2.4
Closes https://github.com/python/miss-islington/issues/38
> Don't prefix the commit message with branch number.

- requirements.txt
It fixed the bug with backport PR title.
> Use cherry-picker v 0.2.5

- README.rst
> Fix typo on README

- backport/status_change.py
- tests/test_status_change.py
Closes https://github.com/python/miss-islington/issues/53
> Remove the backport PR number, retain the original PR number

- README.rst
Once a core dev approved it and all CI passed.
> Readme: Mention that backport PR will be automatically merged

- miss_islington/delete_branch.py
- tests/test_delete_branch.py
Save one API call.
Closes https://github.com/python/miss-islington/issues/97
> Don't say thanks after PR has been closed.

- dev-requirements.txt
- miss_islington/util.py
- tests/test_util.py
> Improve the test coverage for util.py

- miss_islington/status_change.py
- tests/test_status_change.py
Closes https://github.com/python/miss-islington/issues/188
> Leave a comment if failed to merge PR.

- miss_islington/status_change.py
- tests/test_status_change.py
Ensure we're sending in a string instead of a list.
> Fix the problem with automerging

- miss_islington/__main__.py
- requirements.txt
> Add Sentry

- README.rst
Changed [link](https://www.youtube.com/watch?v=yp_l5ntikaU) from the [old one](https://www.youtube.com/watch?v=k3jt5ibfRzw&feature=youtu.be) which does not work any more.
> Change youtube link to the witch sketch.

- runtime.txt
> Use Python 3.6.9 runtime

- miss_islington/status_change.py
- miss_islington/util.py
- tests/test_util.py
> Remove BPO link and strip newlines from commit body

- runtime.txt
> Use Python 3.7.7 runtime

- runtime.txt
> Use Python 3.7.8

- miss_islington/status_change.py
- tests/test_status_change.py
> Remove 'Automerge-Triggered-By' text when removing the automerge label

- miss_islington/status_change.py
- miss_islington/util.py
- tests/test_status_change.py
Look up conclusions from check runs in addition to status checks.
Ensure all check runs have completed.
Ensure there is no "failure" or "timed_out" result from the check runs
Fixes https://github.com/python/miss-islington/issues/375
> Fix Automerge functionality

- Procfile
The command line invocation for celery was changed in v5.
> Upgrade to celery 5.0

- miss_islington/__main__.py
Closes https://github.com/python/miss-islington/issues/390
> Add Sentry CeleryIntegration

- miss_islington/tasks.py
Closes https://github.com/python/miss-islington/issues/446
Signed-off-by: Mariatta <mariatta@python.org>
> Prep for 3.10 beta release: Use the `main` branch

- runtime.txt
Heroku has already support for it: https://devcenter.heroku.com/articles/python-runtimes#selecting-a-runtime
> Update runtime to the latest Python3.9 release

- .github/workflows/ci.yml
- requirements.txt
Building off #619 (closes #619). X-ref https://github.com/aio-libs/aiohttp/issues/7675.
> Test with Python 3.12 in CI

- miss_islington/tasks.py
Set the broker_connection_retry_on_startup
> Fix deprecation warning on Celery.

- .github/workflows/ci.yml
- .github/workflows/lint.yml
Like https://github.com/python/blurb/pull/32, and with https://github.com/woodruffw/zizmor security fixes.
> CI: Lint and test via uv
