- backport/util.py
The `html_url` field takes us to the actual comment on GitHub.
`url` field takes us to an API JSON response.
> Use html_url field instead of url

- backport/status_change.py
There were cases where `data["commit"]["committer"]` is null.
> Check if payload contains "committer" info.

- backport/__main__.py
- backport/tasks.py
Instead of setting up the repo when the main app started,
do it when the worker app is started.
Use celery bootsteps.
> Move setting up CPython repo to the worker app.

- README.rst
- miss_islington/tasks.py
- miss_islington/util.py
Update the readme indicating that the PR will be assigned to the
core dev for follow up.
> Assign the PR that failed to be backported to the core dev.

- miss_islington/status_change.py
- miss_islington/util.py
- tests/test_util.py
> Normalize commit messages on automerge

- requirements.txt
As I see a lot of changes between 1.2.2 and 1.3, I think we should start by reverting, and then take the time to understand what's going wrong.
see https://github.com/python/miss-islington/issues/219
> Revert cherry_picker to 1.2.2.

- miss_islington/backport_pr.py
- tests/test_backport_pr.py
Closes https://github.com/python/miss-islington/issues/228
> Retry failed backport due to redis ConnectionError up to 5 times

- miss_islington/backport_pr.py
- tests/test_backport_pr.py
If celery or redis is down, then we can't perform "sleep".
Heroku's web dyno times out after 30 seconds. 😥
> Don't retry failed backport. Just leave a message.

- README.rst
Add the information to README that miss-islington can also merge regular PRs if `automerge` label is added to them and it is approved by a Core Dev.
> miss-islington can also do regular non-backport merges

- miss_islington/tasks.py
When something terribly wrong has happened the bot puts "sorry" in front of the message except for the "Something is wrong... I can't backport for now" message
> Add "sorry" in front of  "Something is wrong... I can't backport for now"

- miss_islington/status_change.py
- tests/test_status_change.py
This is based on #275 (the first commit is the commit from #275, with corrected issue number in the commit message), and contains a minor missing fix from that PR.
Closes #270, supersedes #275.
> Use GH: rather than @ to tag core devs in Automerge-Triggered-By

- miss_islington/tasks.py
- tests/test_backport_pr.py
We upgraded the redis environment on Heroku a couple days ago. In the new environment, the ``REDIS_URL`` environment variable was changed to ``HEROKU_REDIS_MAROON_TLS_URL``.
Updated the code where we were hardcoding it to the old to url.
Fixes #462
> Fix the redis URL

- miss_islington/__main__.py
- miss_islington/tasks.py
This moves the CeleryIntegration setup to the Celery worker module. `__main__.py` isn't imported by the Celery worker so the integration wasn't working.
> Setup Sentry in the Celery worker

- miss_islington/status_change.py
Fixes inconsistent statements such as [this one](https://github.com/python/cpython/pull/29669#issuecomment-974678543) [(more)](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Aopen+%22success+%E2%9D%8C%22):
"it's a success ❌"
The `success` boolean was added in #382 without updating the message.
> Fix incorrect success statement in status change comment

- .coveragerc
- .github/workflows/ci.yml
- miss_islington/check_run.py
- miss_islington/status_change.py
- miss_islington/tasks.py
- miss_islington/util.py
- pytest.ini
- tests/test_backport_pr.py
- tests/test_check_run.py
- tests/test_status_change.py
- tests/test_util.py
CPython is now using cpython-cla-bot, and we're not relying on the CLA Signed label anymore.
CLA signed is now a status check on the CI.
Also remove the DeprecationWarning from pytest by adding pytest.ini
> Don't check for "CLA signed" label.

- miss_islington/status_change.py
- tests/test_check_run.py
- tests/test_status_change.py
Closes #564.
Split out the `"succes"` check from the timed out check so we can record both states.
> Fix status check comment for timed out or failed checks

- miss_islington/status_change.py
- tests/test_status_change.py
Refs https://github.com/python/miss-islington/pull/565#issuecomment-1237431097
The logic introduced in https://github.com/python/miss-islington/pull/565 was not correct as the `if ... if ... else` was place incorrectly.
I didn't catch this as the previous tests don't actually test for the actual message being commented, but only check if a comment is being posted. This fixes this and updates all test that check for comment posting in the `status_change` tests.
Pinging @ezio-melotti for a review.
Sorry for the confusion caused! I should have seen this gap in the tests when I first worked on this issue.
> Fix faulty logic for success/failure comment

- miss_islington/status_change.py
- tests/test_status_change.py
> Disable CI status change comments unless the "automerge" label is used

- miss_islington/check_run.py
- miss_islington/status_change.py
- tests/test_check_run.py
> Disable miss-islington comments in check_run as well

- miss_islington/tasks.py
In my experience, removing and re-adding the label almost always works. Ideally we'd fix Miss Islington so this error doesn't happen, but in the meantime let's point people to the easiest workaround.
> Give better instructions for "I had trouble checking out..."

- dev-requirements.txt
We're using a GitHub action and this package is not usable anymore.
> Remove `codecov`

- .github/workflows/ci.yml
- .gitignore
- tox.ini
Instead of explicitly using https://github.com/actions/cache, we can use the caching now built into https://github.com/actions/setup-python: https://github.com/actions/setup-python#caching-packages-dependencies
Also:
* Allow testing feature branches and triggers via the UI
* Use `fail-fast: false` so if one fails, allow the others to complete. Helps debugging - did a single job fail, or do all fail?
* Enable colour for more readable test output
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Simplify CI config for caching

- requirements.txt
To fix the build for 3.9-3.11:
https://github.com/python/miss-islington/actions/runs/6336037275/job/17208313322
> Bump celery to 5.3.4

- miss_islington/__main__.py
- miss_islington/backport_pr.py
- miss_islington/tasks.py
- tests/test_backport_pr.py
Use Installation Access Token instead of Personal Access token.
Note that the Personal Access Token is still needed during cherry-picking/backport process, as there is no GitHub API for cherry-picking.
Deployment tasks:
> Miss-islington as a GitHub App

- requirements.txt
This workaround was added to deal with:
* https://github.com/celery/kombu/issues/1600
The issue is now fixed, so it should be safe to remove it.
> Remove workaround from requirements.txt

- .github/workflows/ci.yml
- tox.ini
Pending CFFI support for 3.13, should be available in CFFI 1.17.0 soonish:
* https://github.com/python-cffi/cffi/issues/105
> Test Python 3.13

- README.rst
These README mentions are often forgotten.
We dropped 3.7 and 3.8 in 2021 (https://github.com/python/miss-islington/pull/478) and 3.9 and 3.10 in 2023 (https://github.com/python/miss-islington/pull/657).
See https://github.com/python/miss-islington/blob/main/runtime.txt and https://github.com/python/miss-islington/blob/main/.github/workflows/ci.yml for supported versions.
> README: Remove outdated line about Python 3.6+

- miss_islington/delete_branch.py
- miss_islington/tasks.py
- requirements.txt
We quite regularly get failures due to sporadic GitHub network issues. This change introduces handling of a new `cherry_picker.GitHubException` to automatically abort and recover a sane state of the repository.
Previously, the repository was left in a PR_CREATING state, which was not expected by cherry-picker on a re-run, which made miss-islington stall until manually restarted.
> Acknowledge network issues from GitHub

- .pre-commit-config.yaml
- dev-requirements.txt
- requirements.txt
Followup to https://github.com/python/miss-islington/pull/710.
* https://pypi.org/project/cherry-picker/2.5.0/
* https://github.com/python/cherry-picker/releases/tag/cherry-picker-v2.5.0 
Also add requirements-txt-fixer to pre-commit.
> cherry-picker 2.5.0 has been released
